# Generated by Django 4.1.2 on 2024-07-01 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(db_column='idAlbum', primary_key=True, serialize=False)),
                ('nombre_disco', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('precio', models.IntegerField()),
                ('portada', models.ImageField(default=None, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(db_column='idArtista', primary_key=True, serialize=False)),
                ('nombre_artista', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id_formato', models.AutoField(db_column='idFormato', primary_key=True, serialize=False)),
                ('formato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(db_column='idMensaje', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(db_column='idCompra', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('discos', models.ManyToManyField(related_name='compras', to='discos.album')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='id_artista',
            field=models.ForeignKey(db_column='idArtista', on_delete=django.db.models.deletion.CASCADE, to='discos.artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='id_formato',
            field=models.ForeignKey(db_column='idFormato', on_delete=django.db.models.deletion.CASCADE, to='discos.formato'),
        ),
        migrations.AddField(
            model_name='album',
            name='id_genero',
            field=models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='discos.genero'),
        ),
    ]
