# Generated by Django 4.1.2 on 2024-07-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='finalizada',
            field=models.BooleanField(db_column='finalizada', default=False),
        ),
    ]
