# Generated by Django 4.1.2 on 2024-07-02 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0003_rename_nacionalidad_artista_pais'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('id_artista', 'nombre_disco', 'fecha_lanzamiento', 'precio', 'id_formato', 'id_genero')},
        ),
        migrations.AlterUniqueTogether(
            name='artista',
            unique_together={('nombre_artista', 'pais')},
        ),
    ]
