# Generated by Django 4.1.2 on 2024-07-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0005_alter_formato_formato_alter_genero_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(db_column='leido', default=False),
        ),
    ]
