# Generated by Django 4.1.2 on 2024-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0006_mensaje_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
